### ISSUE TITLE
这是只支持3.9.6.33版本，还是向下兼容？

### ISSUE THREAD

**Issue by JoeQinOvO** [SuxueCode/WechatPCMsgBakTool#1]
如果只支持一个版本的话，普适性太差了，好像可以自动获取基址的，python的pymem都能做到。不过我很喜欢作者的图形化思路！！！点赞

**Comment by JoeQinOvO** [comment]
我测试微信3.9.0.28版本，提示这个，微信确认已打开，我用sharpWXdump是可以获取自己的秘钥的。
![image](https://github.com/SuxueCode/WechatPCMsgBakTool/assets/104407735/2aa6a194-5007-4fc1-93e5-448a270e946c)

**Comment by SuxueCode** [comment]
目前是只支持一个版本，即README里面说的那个版本
我前段时间也有看到SharpWxDump版本的作者那里合并了自动查找，只是我还没更新
本来这个项目就是想传上来看看反响先
有需要的话，回头就更新一下

**Comment by JoeQinOvO** [comment]
我觉得这个是很好的！图形化界面解密的目前我看了只有一个你的，和另一个java写的，但是另外一个需要javaFX环境，配置起来很头疼，而C#的优势就很大。建议你把readme里多加点图片说明，写详细点，微信上的公众号回来搬运给你热度的

**Comment by SuxueCode** [comment]
回头应该会在b站发一个教程
C#的本身优势之一就是低成本GUI，开销很小，普遍适用

**Comment by SuxueCode** [comment]
你好，经过评估，目前自动查找密钥的功能目前看似乎并不怎么有效
因此目前只是暂时将版本支持文件拆分出来，方便后续维护
不过微信从某个版本后开始转向64位的支持，备份程序也是基于64位的获取代码写的，考虑到后续维护，目前暂时也没有向老版本支持的计划
如果后续x64版本的版本支持，在version.json添加即可完成版本支持
