### ISSUE TITLE
工作区找不到微信进程，微信PC版本为：3.9.8.15

### ISSUE THREAD

**Issue by KMnO4-zx** [SuxueCode/WechatPCMsgBakTool#10]
您好，我在工作区找不到微信进程，微信PC版本为：3.9.8.15
很棒的的工作，我想把自己的聊天记录提取，然后训练一个模型。
希望可以得到您的帮助！

![image](https://github.com/SuxueCode/WechatPCMsgBakTool/assets/77671993/f09772c1-0d92-4e9a-afae-cef35de51f15)

**Comment by KMnO4-zx** [comment]
嗯嗯嗯 好的 感谢您的回复， 那要怎么进群呢？

**Comment by SuxueCode** [comment]
项目页面写有
815054692

**Comment by KMnO4-zx** [comment]
好的 好的！

**Comment by SuxueCode** [comment]
v0.6.0.2 fix
