### ISSUE TITLE
提示密钥获取失败，是需要修改基址吗？

### ISSUE THREAD

**Issue by xngx2013** [SuxueCode/WechatPCMsgBakTool#2]

**Comment by SuxueCode** [comment]
请确认微信版本是否是3.9.6.33，往前的版本可能不支持，往后的话找到新基址，配置进version.json即可

**Comment by SuxueCode** [comment]
这个我今天在新机器实验了一下兼容性，复现了这个问题，目前已经定位到问题了
晚点发个版本修复一下，你可以再试试

**Comment by SuxueCode** [comment]
试试v0.3.1版本看看
