### ISSUE TITLE
微信每次更新后，基址都会变

### ISSUE THREAD

**Issue by 1402686212** [SuxueCode/WechatPCMsgBakTool#4]
作者你好，微信每次更新后，基址都会变，有办法自动从进程中提取到代码吗？或者有通用的调试获取到微信的基址码吗？

**Comment by SuxueCode** [comment]
目前大家普遍的一个做法是扫描内存，但是自动扫内存不一定管用，可能会需要多次扫描才会出
如果是调试获取的话，也是大概这个原理
你可以参考一下其他项目有的会说用dbg去调试，这个我不擅长
