### ISSUE TITLE
大佬，最新版本能否打包下release版？

### ISSUE THREAD

**Issue by liu-hanxu** [SuxueCode/WechatPCMsgBakTool#5]

**Comment by SuxueCode** [comment]
最新版本仅更新了version.json支持了3.9.7.29，你把json覆盖一下就好了，其他没改啥

**Comment by LiuDilongNJ** [comment]
大佬.更新了json闪退

**Comment by SuxueCode** [comment]
@LiuDilongNJ 校验下json格式是否正确，十有八九json格式有问题，我那里没做容错

**Comment by LiuDilongNJ** [comment]
json没错,解密的时候闪退

**Comment by SuxueCode** [comment]
@LiuDilongNJ 说错了，是事件查看器

**Comment by LiuDilongNJ** [comment]
3.9.7.29

**Comment by LiuDilongNJ** [comment]
![image](https://github.com/SuxueCode/WechatPCMsgBakTool/assets/109188679/ad189157-548d-4407-83df-e192d76c6599)
![image](https://github.com/SuxueCode/WechatPCMsgBakTool/assets/109188679/ebf0a5e9-6845-4426-aa1a-a94cb9a2f1f6)

**Comment by LiuDilongNJ** [comment]
![image](https://github.com/SuxueCode/WechatPCMsgBakTool/assets/109188679/3ad56657-3c5e-466a-8c40-6e8636f3e10b)
![image](https://github.com/SuxueCode/WechatPCMsgBakTool/assets/109188679/8fcbdb91-3745-4600-8ded-dc0875a3c515)

**Comment by SuxueCode** [comment]
你好，看这报错，应该是json的问题，在jsonconvert的时候出错了
麻烦贴一下version.json

或者试试下面这个
`[
	{
		"Version": "3.9.6.33",
		"BaseAddr": 62031872
	},{
		"Version":"3.9.7.25",
		"BaseAddr": 63484032
	},{
		"Version":"3.9.7.29",
		"BaseAddr": 63488256
	}
]`

**Comment by LiuDilongNJ** [comment]
![image](https://github.com/SuxueCode/WechatPCMsgBakTool/assets/109188679/34b55115-a964-454e-af42-fd51ca825c8b)

**Comment by LiuDilongNJ** [comment]
新发的这个可以,谢谢大佬

**Comment by SuxueCode** [comment]
相关错误已处理，并新增全局异常log
