### ISSUE TITLE
关于导出成功后的疑问

### ISSUE THREAD

**Issue by gyco** [SuxueCode/WechatPCMsgBakTool#7]
1.导出记录后 可以明文查看吗 如何操作使用？
2,对应记录在哪里，好像只导出对应联系人的网名，可以添加备注信息嘛！

**Comment by SuxueCode** [comment]
导出记录后就是明文，默认是在程序根目录的工作区文件夹内，workspace内。
如果你是需要db的话，也是在workspace内decdb文件夹
目前导出后，文件名都是以用户的原始id命名，备注信息考虑到转义问题，暂不考虑，但是也不是不能做

**Comment by gyco** [comment]
对于导出html的方式 似乎不可行.html文件大小始终为1kb 是因为微信版本还是啥原因呢?
decdb中的文件是可以打开的 但因为是数据库文件 不是特别直观 希望能修复一下html的这个功能 
微信版本是最新的3.9.7.29

**Comment by SuxueCode** [comment]
你可以加一下群：815054692
我看看啥问题

**Comment by SuxueCode** [comment]
群内了解情况后未再次反馈，关闭issue
