### ISSUE TITLE
导出转发的公众号文章的标题和链接

### ISSUE THREAD

**Issue by saxyx** [SuxueCode/WechatPCMsgBakTool#8]
我喜欢把公众号文章转发到文件传输助手里，但目前的导出的html上显示的是暂未支持的消息。请问有计划添加把转发的公众号文章的标题和链接导出的功能吗？

**Comment by SuxueCode** [comment]
我看看，应该没啥问题，如果没啥特殊情况，下个版本支持

**Comment by SuxueCode** [comment]
v0.5 已经更新支持

**Comment by saxyx** [comment]
> v0.5 已经更新支持

非常感谢！

**Comment by saxyx** [comment]
> v0.5 已经更新支持

已经登陆微信，新增工作区时没有找到打开的微信进程

**Comment by SuxueCode** [comment]
加下群，我看看啥情况
