### ISSUE TITLE
0.6版本新建工作区时报错

### ISSUE THREAD

**Issue by SeaPeak520** [SuxueCode/WechatPCMsgBakTool#9]
新建工作区时报错，检查过路径没问题，微信版本3.9.6.33
![image](https://github.com/SuxueCode/WechatPCMsgBakTool/assets/114002983/db34a7d7-58cd-46c5-801b-1c66843aa601)

![image](https://github.com/SuxueCode/WechatPCMsgBakTool/assets/114002983/789f63ad-4b80-47f7-a895-6f341ddeb447)

**Comment by SuxueCode** [comment]
看一下程序根目录有err.log嘛，有的话贴上来

**Comment by SeaPeak520** [comment]
不好意思，创建工作区的问题：程序目录解压c盘，然后c盘空间不足导致的，换到其他盘运行就能创建
但还是出现解密的问题，没有err.log日志
![image](https://github.com/SuxueCode/WechatPCMsgBakTool/assets/114002983/403d5787-4f42-423d-83a8-882ca7265d3b)

**Comment by SuxueCode** [comment]
你是移动过文件夹是吗，尝试下把目录下workspace删掉，重新新建工作区试试

**Comment by SeaPeak520** [comment]
之前更改过微信默认文件夹，试过workspace删掉重新新建工作区，还是会报错密钥错误

**Comment by SuxueCode** [comment]
麻烦进群让我see see

**Comment by SuxueCode** [comment]
v0.6.0.1修复
